name: CI

on:
  push:
  pull_request:

jobs:
  main:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos ]
        ruby: [ '2.6', '2.7', '3.0' ]

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('Gemfile', 'mnogootex.gemspec') }}
          restore-keys: gems-${{ matrix.os }}-${{ matrix.ruby }}-

      - name: Install Ruby gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 3 --retry 3

      - name: Run tests
        run: bundle exec rake spec:rspec
